---
abstract: 'Get information on arbitrary processes in Windows NT'
author:
  - 'Tom Wyant (wyant at cpan dot org)'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.62, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Win32-Process-Info
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: '0'
  File::Spec: '0'
  Time::Local: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/uperl/Win32-Process-Info/issues
  homepage: https://metacpan.org/pod/Win32::Process::Info
  repository: https://github.com/uperl/Win32-Process-Info.git
version: '1.022'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
